### PR TITLE
More polished code and allowing the insertion of multiple lines in a single call

### PR DESCRIPTION
**Pull request by xBu3n0**

### CODE REVIEW

**Comment by jcrodriguezt** [comment]
Hello, sorry for not getting to this earlier. Could you please share with me what issues were you trying to address with this improvement?   I mean, the multiple lines part of your comment.

I'm glad for your code cleanup.. I've been a little bit to lazy to dedicate some time to it. I just made it work for my needs which I don't think are too special.

**Comment by xBu3n0** [comment]
Hi, thanks for merging the branch, the changes I made were because I'm using it and I wanted to use more tools that Laravel provides but it wasn't possible with the old library, and as I used your branch as a base, I made the pull request so that other people can use.
In the comments section it was so that, if someone else tries to use it, know that it will not be possible with the current update (it was not possible in the old version either)

**Comment by jcrodriguezt** [comment]
Have you tried whereBetween clauses? In many cases it's not working. I've
had not much time to debug it yet

**Comment by xBu3n0** [comment]
No, I hadn't tested this version that you accepted, but this morning's update is already working with `->between` and `->notBetween`

**Comment by jcrodriguezt** [comment]
Oh, I see.
I'll give it a try and if anything changes I'll let you know.

**Comment by xBu3n0** [comment]
I closed the merge of this functionality because with each update I am doing the merge, possibly polluting the fork due to the delay in merges, if I want to use the resources I find it easier to use my branch, for my control too, any functionality you want and/or problems encountered comment in `xBu3n0/laravel-sybase`.

**Comment by jcrodriguezt** [comment]
Actually I was thinking about a collab
..let me know what you think

**Comment by xBu3n0** [comment]
It's a collaboration, people who are using your library can take advantage of what I wrote, and the way I wrote it, people can make changes more easily, but I have already rewrote almost the entire library, and for the work I would like to leave it on my profile without depending on merging others (even more so due to the delay in the merge process and me not having control of future updates (e.g. The merge of the simple `null:` instead of `:` on the last pull request, a small error, but because it's not from my branch it gets stuck)).

In the end it will look like my code on your profile/branch but outdated.

**Comment by jcrodriguezt** [comment]
No problem, I understand.
Thanks for your help

**Pull request merged**
